# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeclaw" do
  name "kubeclaw"
  desc "CLI for managing KubeClaw Helm chart installations on Kubernetes"
  homepage "https://kubeclaw.ai"
  version "0.1.5-cli.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeclaw"

  on_macos do
    on_intel do
      url "https://github.com/iMerica/kubeclaw/releases/download/v#{version}/kubeclaw_darwin_amd64.tar.gz"
      sha256 "bb5e24573f9d90548a19e28a384ba78a0a8ff380d93dc4594011aa8528c8dfea"
    end
    on_arm do
      url "https://github.com/iMerica/kubeclaw/releases/download/v#{version}/kubeclaw_darwin_arm64.tar.gz"
      sha256 "e50cd6098613d833a2d62272644860bccd6084f09511b3e20c7765d5bc8500e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iMerica/kubeclaw/releases/download/v#{version}/kubeclaw_linux_amd64.tar.gz"
      sha256 "d242106208f79911e392e9753dc366537bcb5e3819e50c8541565be718058680"
    end
    on_arm do
      url "https://github.com/iMerica/kubeclaw/releases/download/v#{version}/kubeclaw_linux_arm64.tar.gz"
      sha256 "7844493644e31a432620d51ac8ba97a6712206fcba68818a28ff8cdc50803ccb"
    end
  end

  # No zap stanza required
end
