# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeclaw < Formula
  desc "CLI for managing KubeClaw Helm chart installations on Kubernetes"
  homepage "https://kubeclaw.ai"
  version "0.1.7-cli.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iMerica/kubeclaw/releases/download/v0.1.7-cli.0/kubeclaw_darwin_amd64.tar.gz"
      sha256 "51260a00e41796b4d1be812ed1407aaab253c2d6260b3724cf4ab11b31c33649"

      define_method(:install) do
        bin.install "kubeclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iMerica/kubeclaw/releases/download/v0.1.7-cli.0/kubeclaw_darwin_arm64.tar.gz"
      sha256 "19949f572bd98b9ec21e74588b1a8d1b6a175d9041504693a2242f4d4bd4ec4a"

      define_method(:install) do
        bin.install "kubeclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iMerica/kubeclaw/releases/download/v0.1.7-cli.0/kubeclaw_linux_amd64.tar.gz"
      sha256 "227949fe45f5b12f0036b7f7cdb1f3c0005a37ecf8209e264d7a041a74fbd193"
      define_method(:install) do
        bin.install "kubeclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iMerica/kubeclaw/releases/download/v0.1.7-cli.0/kubeclaw_linux_arm64.tar.gz"
      sha256 "7cb3987a59cbf6a51981c34da66eb26d665660309e6e157dd4983c0964a192d4"
      define_method(:install) do
        bin.install "kubeclaw"
      end
    end
  end
end
