{{- if and .Values.gatewayAPI.enabled .Values.gatewayAPI.controller.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayAPI.controller.gatewayClassName }}
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}
