{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeclaw.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- if and .Values.litellm.enabled .Values.litellm.masterkey }}
  LITELLM_API_KEY: {{ .Values.litellm.masterkey | b64enc | quote }}
  {{- end }}
  {{- if .Values.github.auth.token }}
  GH_TOKEN: {{ .Values.github.auth.token | b64enc | quote }}
  GITHUB_TOKEN: {{ .Values.github.auth.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.jira.auth.token }}
  JIRA_API_TOKEN: {{ .Values.jira.auth.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.linear.auth.token }}
  LINEAR_API_KEY: {{ .Values.linear.auth.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.asana.auth.token }}
  ASANA_PAT: {{ .Values.asana.auth.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.trello.auth.apiKey }}
  TRELLO_API_KEY: {{ .Values.trello.auth.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.trello.auth.token }}
  TRELLO_TOKEN: {{ .Values.trello.auth.token | b64enc | quote }}
  {{- end }}
{{- end }}
